const translationMap = {
    "clear": "clear",
    "sunny": "clear",
    "partly cloudy": "partly_cloudy",
    "cloudy": "cloudy",
    "overcast": "overcast",
    "mist": "mist",
    "patchy rain possible": "rain",
    "patchy snow possible": "snow",
    "patchy sleet possible": "sleet",
    "patchy freezing drizzle possible": "drizzle",
    "thundery outbreaks possible": "thunderstorms",
    "blowing snow": "snow",
    "blizzard": "snow",
    "fog": "fog",
    "freezing fog": "fog",
    "patchy light drizzle": "drizzle",
    "light drizzle": "drizzle",
    "freezing drizzle": "drizzle",
    "heavy freezing drizzle": "drizzle",
    "patchy light rain": "rain",
    "light rain": "rain",
    "moderate rain at times": "rain",
    "moderate rain": "rain",
    "heavy rain at times": "rain",
    "heavy rain": "rain",
    "light freezing rain": "rain",
    "moderate or heavy freezing rain": "rain",
    "light sleet": "sleet",
    "moderate or heavy sleet": "sleet",
    "patchy light snow": "snow",
    "light snow": "snow",
    "patchy moderate snow": "snow",
    "moderate snow": "snow",
    "patchy heavy snow": "snow",
    "heavy snow": "snow",
    "ice pellets": "snow",
    "light rain shower": "rain",
    "moderate or heavy rain shower": "rain",
    "torrential rain shower": "rain",
    "light sleet showers": "sleet",
    "moderate or heavy sleet showers": "sleet",
    "light snow showers": "snow",
    "moderate or heavy snow showers": "snow",
    "patchy light rain with thunder": "thunderstorms_rain",
    "moderate or heavy rain with thunder": "thunderstorms_rain",
    "patchy light snow with thunder": "thunderstorms_snow",
    "moderate or heavy snow with thunder": "thunderstorms_snow",
    "patchy rain nearby": "rain",
    "haze": "haze"
}

const dualValues = ['clear','partly_cloudy','overcast','thunderstorms','fog']

export {translationMap, dualValues};